data: mock

data_file: mock_data.npz

sim: smdpl

param: mvir

file_ext: /home/lom31/emcee_fits/july_2020/

output: lin_test_nong.h5

ndim: 2

nwalkers: 20

nsteps: 10000

prior_ranges:
     ro: [0.1,450.0]
     g: [-1.0,2.0]

guess: [10.0,1.8]