data: zehavi

data_file: zehavi_data_file_20

sim: smdpl

param: vmax

file_ext: /home/lom31/emcee_fits/june_2020/

output: zehavi_smdpl_vmax_m20.h5

ndim: 5

nwalkers: 20

nsteps: 50000

prior_ranges:
     logMmin_r: [1.0,4.0]
     sigma_logM_r: [0.01,2.5]
     alpha_r: [0.85,5.0]
     logM0_r: [1.0,4.0]
     logM1_r: [1.0,4.0]

guess: [2.21, 0.015, 2.59, 2.18, 2.456]
